export const GAME_EVENTS = {
  NOTIFICATION_CLOSED: 'NOTIFICATION_CLOSED',
  CHOOSE_CARD: 'CHOOSE_CARD',

  CHOOSE_UNKNOWN_CARD: 'CHOOSE_UNKNOWN_CARD',
  UNKNOWN_ACTIVE: 'UNKNOWN_ACTIVE',
  MOVE_CAMERA_TO_WINDOW: 'MOVE_CAMERA_TO_WINDOW',
  CHOOSE_ACTIVE: 'CHOOSE_ACTIVE',

  SEAL_WINDOW: 'SEAL_WINDOW',
  REPAIR_WINDOW: 'REPAIR_WINDOW',

  REDIRECT: 'REDIRECT',
};
